import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    absolute: "", //use this ti ignore  template
    default: "Next.js Tutorial -Default CodeEvolution",
    template: "%s | Code-Evolution", //suffix for all will be Code Evolution
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: // header,
// footer,
{
  children: React.ReactNode;
  header: React.ReactNode;
  footer: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          Header
          {/* {header} */}
          <Link href="/">Go To HOME</Link>
        </header>

        <br />
        {children}

        <footer>
          {/* {footer} */}
          Footer
        </footer>
      </body>
    </html>
  );
}
