import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Blog",
  },
  // description: "Generated by Next.js",
};
function page() {
  return <div>My Blog Page</div>;
}

export default page;
